### ISSUE TITLE
how to compile this project?

### ISSUE THREAD

**Issue by jiangdiankun** [Sean10/Bank#1]
hi, whether to support Makefile to compile this project? thank you

**Comment by Sean10** [comment]
* Linux GUI界面下，安装Qt Creator(Qt 5)
* 安装openSSL，根据openSSL安装版本及路径修改common.pri中openSSL库依赖路径
* 支持c++ 14的编译器
    * g++ version >= 5
    * clang++ version > 3.4

然后Qt编译运行即可

**Comment by Sean10** [comment]
No additional info, close the issue
